ARG IMAGE_NAME
FROM ${IMAGE_NAME}

# This contains pre-populated data for the uptime-kuma application. The user credentials are:
# - Username: polymesh
# - Password: polymesh1
COPY kuma.db /app/data/kuma.db